# Generated by Django 4.0.3 on 2022-04-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.ManyToManyField(to='ecomadmin.subcategoria'),
        ),
    ]
