# Generated by Django 4.0.3 on 2022-03-29 18:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('nombre_sis', models.CharField(max_length=200)),
                ('existencia_eu', models.IntegerField(default=0)),
                ('existencia_av', models.IntegerField(default=0)),
                ('existencia_mr', models.IntegerField(default=0)),
                ('existencia_ml', models.IntegerField(default=0)),
                ('precio', models.IntegerField(default=0)),
                ('en_oferta', models.BooleanField(default=False)),
                ('precio_oferta', models.IntegerField(default=0)),
                ('tasa', models.IntegerField(choices=[(0, 0), (5, 5), (10, 10)])),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecomadmin.grupoproducto')),
            ],
        ),
        migrations.DeleteModel(
            name='Formula',
        ),
        migrations.RenameModel(
            old_name='CatalogoProducto',
            new_name='ProductoCatalogo',
        ),
        migrations.DeleteModel(
            name='PresentacionProducto',
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_catalogo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomadmin.productocatalogo'),
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('id_grupo', 'id_producto')},
        ),
    ]
