# Generated by Django 4.0.3 on 2022-04-06 11:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='detalle',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
