# Generated by Django 4.0.3 on 2022-04-06 13:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0002_producto_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='detalle',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
