# Generated by Django 4.0.3 on 2022-03-30 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0002_producto_delete_formula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(3)])),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
