# Generated by Django 4.0.3 on 2022-04-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0004_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('descripcion', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='especies',
            field=models.ManyToManyField(to='ecomadmin.especie'),
        ),
    ]
