# Generated by Django 4.0.3 on 2022-03-30 18:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0004_rename_id_grupo_producto_grupo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre_sis',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='producto',
            name='clasificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecomadmin.clasificacionproducto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='linea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ecomadmin.lineaproducto'),
        ),
        migrations.AddField(
            model_name='productocatalogo',
            name='codigo_formula',
            field=models.CharField(max_length=3, null=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AddField(
            model_name='productocatalogo',
            name='descripcion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
