# Generated by Django 4.0.3 on 2022-04-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0005_especie_producto_especies'),
    ]

    operations = [
        migrations.AddField(
            model_name='especie',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='especie',
            name='descripcion',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
