# Generated by Django 4.0.3 on 2022-04-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0007_alter_especie_options_imagenproducto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenproducto',
            options={'ordering': ['posicion']},
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='static/imagenes/'),
        ),
    ]
