# Generated by Django 4.0.3 on 2022-04-13 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0009_alter_producto_especies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
