# Generated by Django 4.0.3 on 2022-04-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0010_remove_producto_imagen'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imagenproducto',
            unique_together=set(),
        ),
    ]
