# Generated by Django 4.0.3 on 2022-04-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0011_alter_imagenproducto_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='posicion',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterUniqueTogether(
            name='imagenproducto',
            unique_together={('producto', 'posicion')},
        ),
    ]
