# Generated by Django 4.0.3 on 2022-04-13 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0012_alter_imagenproducto_posicion_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imagenproducto',
            unique_together=set(),
        ),
    ]
