# Generated by Django 4.0.3 on 2022-04-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0013_alter_imagenproducto_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='especies',
            field=models.ManyToManyField(to='ecomadmin.especie'),
        ),
    ]
