# Generated by Django 4.0.3 on 2022-04-13 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0014_alter_producto_especies'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imagenproducto',
            unique_together={('producto', 'posicion')},
        ),
    ]
