# Generated by Django 4.0.3 on 2022-04-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0015_alter_imagenproducto_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenproducto',
            options={'ordering': ['uploaded']},
        ),
        migrations.AlterUniqueTogether(
            name='imagenproducto',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='uploaded',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='imagenproducto',
            name='posicion',
        ),
    ]
